# Generated by Django 3.2.12 on 2022-02-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20220221_1738"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="make_public",
            field=models.BooleanField(default=True),
        ),
    ]
