# Generated by Django 3.2.12 on 2022-02-21 17:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20220221_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="slug",
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, populate_from="username"),
        ),
    ]
