# Generated by Django 3.2.15 on 2022-08-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_make_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subscription_level",
            field=models.CharField(choices=[("FREE", "FREE"), ("PRO", "PRO")], default="FREE", max_length=15),
        ),
    ]
