# Generated by Django 3.2.15 on 2022-09-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20220828_1740"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PayPalTransaction",
        ),
    ]
