# Generated by Django 3.2.15 on 2022-08-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20220828_0045"),
    ]

    operations = [
        migrations.AddField(
            model_name="paddlewebhook",
            name="alert_name",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
