# Generated by Django 3.2.17 on 2023-03-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_customuser_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_active_django_devs_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
