# Generated by Django 3.2.4 on 2021-07-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Jobs", new_name="Job",),
    ]
