# Generated by Django 3.2.4 on 2021-08-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_rename_jobs_job"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company", old_name="company_email", new_name="email",
        ),
        migrations.RenameField(
            model_name="company", old_name="company_logo", new_name="logo",
        ),
        migrations.RenameField(
            model_name="company", old_name="company_name", new_name="name",
        ),
        migrations.RenameField(
            model_name="company", old_name="company_url", new_name="url",
        ),
        migrations.RenameField(
            model_name="job", old_name="job_listing_url", new_name="listing_url",
        ),
        migrations.RenameField(
            model_name="job", old_name="job_location", new_name="location",
        ),
        migrations.RenameField(
            model_name="job", old_name="job_salary", new_name="salary",
        ),
        migrations.RenameField(
            model_name="job", old_name="job_title", new_name="title",
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
