# Generated by Django 3.2.4 on 2021-08-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_auto_20210814_0255"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job", options={"ordering": ["-created_datetime"]},
        ),
    ]
