# Generated by Django 3.2.4 on 2021-08-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_job_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(name="company", options={"ordering": ["name"]},),
    ]
