# Generated by Django 3.2.4 on 2021-11-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_alter_job_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
