# Generated by Django 3.2.4 on 2021-11-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_job_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
