# Generated by Django 3.2.9 on 2021-11-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_auto_20211105_1458"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_simple",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
