# Generated by Django 3.2.9 on 2021-11-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_alter_job_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="salary",
            new_name="max_yearly_salary",
        ),
        migrations.AddField(
            model_name="job",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="job",
            name="min_yearly_salary",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
