# Generated by Django 3.2.9 on 2021-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0014_auto_20211122_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
