# Generated by Django 3.2.9 on 2021-12-10 20:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0016_alter_job_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, default="django-developer", editable=False, populate_from="title"
            ),
        ),
    ]
