# Generated by Django 3.2.12 on 2022-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_alter_job_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="remote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="time_zone",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
