# Generated by Django 3.2.12 on 2022-04-07 17:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_auto_20220204_1956"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="company_logo",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="Image"),
        ),
    ]
