# Generated by Django 5.0.4 on 2024-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_job_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="submitted_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
