# Generated by Django 5.0.4 on 2024-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_job_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="source_specific_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="submitted_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
