# Generated by Django 5.0.4 on 2024-04-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0020_job_source_specific_data_job_submitted_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="source_specific_data",
        ),
        migrations.AddField(
            model_name="job",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="source",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
