# Generated by Django 5.0.4 on 2024-04-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0021_alter_job_listing_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="updated_datetime",
            field=models.DateTimeField(),
        ),
    ]
