# Generated by Django 5.0.4 on 2024-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0021_remove_job_source_specific_data_job_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
