# Generated by Django 3.0 on 2019-12-04 04:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("website_url", models.URLField(unique=True)),
                ("user_email", models.EmailField(max_length=254)),
                ("website_title", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title"
                    ),
                ),
                (
                    "website_homepage_screenshot",
                    models.ImageField(upload_to="website_homepage_screenshot/"),
                ),
                ("website_description", models.TextField(blank=True)),
                ("website_twitter", models.URLField(blank=True, unique=True)),
                ("website_github", models.URLField(blank=True, unique=True)),
                ("author_name", models.CharField(max_length=100)),
                ("author_email", models.EmailField(max_length=254)),
                ("author_twitter", models.URLField(blank=True)),
                ("author_website", models.URLField(blank=True)),
            ],
        ),
    ]
