# Generated by Django 3.0 on 2019-12-04 05:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="website_title"
            ),
        ),
    ]
