# Generated by Django 3.2.4 on 2021-06-03 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_auto_20210603_0257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="website_additional_info",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="website_description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="website_github",
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="website_requirements",
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="website_twitter",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
