# Generated by Django 3.2.4 on 2021-06-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_auto_20210603_0334"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="project", to="projects.Technology"
            ),
        ),
    ]
