# Generated by Django 3.2.4 on 2021-06-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_technologies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="technologies",
                to="projects.Technology",
            ),
        ),
    ]
