# Generated by Django 3.2.4 on 2021-06-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_auto_20210608_1225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maker",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="technology",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
