# Generated by Django 3.2.4 on 2021-08-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like",
                to="projects.project",
            ),
        ),
    ]
