# Generated by Django 3.0.6 on 2020-05-10 05:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200425_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='website_title'),
        ),
    ]
