# Generated by Django 3.2.4 on 2021-08-20 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0014_alter_like_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
