# Generated by Django 3.0.5 on 2020-05-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_auto_20200510_0530"),
    ]

    operations = [
        migrations.AddField(
            model_name="maker",
            name="interviewed",
            field=models.BooleanField(default=False),
        ),
    ]
