# Generated by Django 3.0.5 on 2020-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_maker_interviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='maker',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
