# Generated by Django 3.2.4 on 2021-08-27 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makers", "0002_alter_maker_table"),
        ("projects", "0016_auto_20210823_2047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="maker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="makers.maker",
            ),
        ),
    ]
