# Generated by Django 3.0.6 on 2020-05-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_is_open_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='indiehackers',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
