# Generated by Django 3.2.4 on 2021-11-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_alter_project_maker"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_for_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="sale_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="technology_suggestions_by_user",
            field=models.TextField(blank=True),
        ),
    ]
