# Generated by Django 3.2.11 on 2022-02-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_alter_comment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="large_company",
            field=models.BooleanField(default=False),
        ),
    ]
