# Generated by Django 3.2.12 on 2022-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_project_large_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_profitable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
