# Generated by Django 3.2.12 on 2022-02-19 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0021_auto_20220204_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logged_in_maker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
