# Generated by Django 3.2.12 on 2022-02-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_project_logged_in_maker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
