# Generated by Django 5.0.4 on 2024-06-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_alter_project_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
