# Generated by Django 5.0.4 on 2024-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_project_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
