# Generated by Django 5.1.6 on 2025-02-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_project_sponsored"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tags",
        ),
    ]
