# Generated by Django 5.1.6 on 2025-02-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_remove_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="date_scraped",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="page_content_html",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="page_content_markdown",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="page_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="page_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
