# Generated by Django 5.1.6 on 2025-02-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_project_date_scraped_project_page_content_html_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="audience_analysis",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
