# Generated by Django 5.1.6 on 2025-02-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_project_audience_analysis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="audience_analysis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
