# Generated by Django 5.1.6 on 2025-02-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_alter_project_audience_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="audience_analysis",
        ),
        migrations.AddField(
            model_name="project",
            name="content_language",
            field=models.CharField(blank=True, help_text="Language the page is written in", max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="content_summary",
            field=models.TextField(blank=True, help_text="Summary of the page content"),
        ),
        migrations.AddField(
            model_name="project",
            name="key_features",
            field=models.TextField(blank=True, help_text="Key features of the project"),
        ),
        migrations.AddField(
            model_name="project",
            name="might_be_spam",
            field=models.BooleanField(default=False, help_text="AI estimation if the project might be spam"),
        ),
        migrations.AddField(
            model_name="project",
            name="page_links",
            field=models.TextField(blank=True, help_text="Links found on the page"),
        ),
        migrations.AddField(
            model_name="project",
            name="pain_points",
            field=models.TextField(blank=True, help_text="Pain points the project addresses"),
        ),
        migrations.AddField(
            model_name="project",
            name="target_audience",
            field=models.TextField(blank=True, help_text="2-3 sentences describing the target audience"),
        ),
        migrations.AddField(
            model_name="project",
            name="usage_instructions",
            field=models.TextField(blank=True, help_text="How to use the product"),
        ),
    ]
