# Generated by Django 5.2.14 on 2026-07-28 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTitleAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_aliases', to='projects.project')),
            ],
        ),
    ]
