repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    exclude: ^migrations/
    language_version: python3.7

- repo: https://github.com/pycqa/isort
  rev: 5.8.0
  hooks:
    - id: isort
      name: isort (python)
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]

# - repo: https://github.com/PyCQA/flake8
#   rev: 3.9.2
#   hooks:
#     - id: flake8

- repo: local
  hooks:
  - id: update-requirements-txt
    name: update-requirements-txt
    description: 'Generate requirements.txt based on poetry.lock'
    entry: poetry
    args: [export, --format, requirements.txt, --output, requirements.txt]
    language: system
    pass_filenames: false
  - id: run-django-html-linter
    name: run-django-html-linter
    exclude: >
        (?x)^(
          templates/django/forms/widgets/.*
          # doesn't work
        )$
    description: 'Run djlint on all template files'
    entry: poetry
    args: [run, djlint, templates, --reformat]
    language: system
    pass_filenames: false
