repos:
- repo: https://github.com/python-poetry/poetry
  rev: 1.1.6
  hooks:
  - id: update-reqs
    name: update-reqs
    entry: poetry export -f requirements.txt > requirements.txt
    language: "script"
    type: [text]