[tool.poetry]
name = "builtwithdjango"
version = "0.1.0"
description = ""
authors = ["Rasul Kireev <me@rasulkireev.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0.5"
django-environ = "^0.4.5"
django-taggit = "^1.2.0"
djangorestframework = "^3.11.0"
gunicorn = "^20.0.4"
requests = "^2.23.0"
sentry_sdk = "^0.14.3"
pillow = "^7.1.1"

[tool.poetry.dev-dependencies]
django-autoslug = "^1.9.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
