[tool.poetry]
name = "builtwithdjango"
version = "0.1.0"
description = ""
authors = ["Rasul Kireev <me@rasulkireev.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0.5"
django-analytical = "^2.6.0"
django-environ = "^0.4.5"
django-taggit = "^1.2.0"
djangorestframework = "^3.11.0"
gunicorn = "^20.0.4"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
