# Generated by Django 3.2.4 on 2021-06-03 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_alter_emails_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="emails",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emails",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
