# Generated by Django 3.2.4 on 2021-06-03 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0003_auto_20210603_0258"),
    ]

    operations = [
        migrations.RemoveField(model_name="emails", name="created_date",),
        migrations.RemoveField(model_name="emails", name="updated_date",),
    ]
