# Generated by Django 3.2.4 on 2021-09-14 16:49

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CistercianDateNftRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("wallet_public_key", models.CharField(max_length=200)),
                ("date_requested", models.DateField(unique_for_date=True)),
                ("sent", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
