# Generated by Django 3.2.4 on 2021-09-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cisterciandatenftrequest",
            name="wallet_public_key",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
