# Generated by Django 3.2.4 on 2021-09-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_auto_20210915_0200"),
    ]

    operations = [
        migrations.AddField(
            model_name="cisterciandatenftrequest",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
