# Generated by Django 3.2.4 on 2021-08-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20210827_1907"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
