# Generated by Django 3.2.11 on 2022-01-23 05:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name="image"),
        ),
        migrations.AddField(
            model_name="post",
            name="unsplashID",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
