# Generated by Django 3.2.11 on 2022-01-23 05:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_auto_20220123_0516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="Image"),
        ),
    ]
