# Generated by Django 3.2.11 on 2022-01-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="thumbnail",
        ),
    ]
