# Generated by Django 3.2.13 on 2022-07-19 03:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_rename_project_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="icon",
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name="Image"),
        ),
        migrations.AddField(
            model_name="post",
            name="level",
            field=models.CharField(
                choices=[("BEGINNER", "BEGINNER"), ("INTERMEDIATE", "INTERMEDIATE"), ("ADVANCED", "ADVANCED")],
                default="BEGINNER",
                max_length=15,
            ),
        ),
    ]
