# Generated by Django 3.2.15 on 2022-09-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_auto_20220719_0313"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="type",
            field=models.CharField(
                choices=[("TUTORIAL", "TUTORIAL"), ("INTERVIEW", "INTERVIEW"), ("UPDATE", "UPDATE")],
                default="TUTORIAL",
                max_length=15,
            ),
        ),
    ]
