# Generated by Django 3.2.4 on 2021-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0010_auto_20210608_1240"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("player_html_embed", models.TextField()),
                ("details", models.TextField()),
                ("show_notes", models.TextField(blank=True)),
                ("transcript", models.TextField(blank=True)),
                (
                    "maker",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="podcast_episodes",
                        to="projects.Maker",
                    ),
                ),
                (
                    "project",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="podcast_episodes",
                        to="projects.Project",
                    ),
                ),
            ],
        ),
    ]
