# Generated by Django 3.2.4 on 2021-08-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_auto_20210608_1240"),
        ("podcast", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="maker",
            field=models.ManyToManyField(
                blank=True, related_name="podcast_episodes", to="projects.Maker"
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="project",
            field=models.ManyToManyField(
                blank=True, related_name="podcast_episodes", to="projects.Project"
            ),
        ),
    ]
