# Generated by Django 3.2.4 on 2021-08-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0002_auto_20210812_1639"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="podcast_episode_thumbnail/"),
        ),
    ]
