# Generated by Django 3.2.4 on 2021-08-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0003_episode_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
