# Generated by Django 3.2.4 on 2021-08-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0006_auto_20210813_0323"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode", options={"ordering": ["-created_datetime"]},
        ),
    ]
