# Generated by Django 3.2.4 on 2021-08-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makers", "0002_alter_maker_table"),
        ("podcast", "0009_alter_episode_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="maker",
            field=models.ManyToManyField(
                blank=True, related_name="podcast_episodes", to="makers.Maker"
            ),
        ),
    ]
