# Generated by Django 3.2.4 on 2021-08-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast", "0010_alter_episode_maker"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="youtube_html_embed",
            field=models.TextField(blank=True),
        ),
    ]
