# Generated by Django 3.2.4 on 2021-08-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Maker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(blank=True, max_length=20)),
                ("last_name", models.CharField(blank=True, max_length=20)),
                ("maker_email", models.EmailField(blank=True, max_length=254)),
                (
                    "maker_profile_image",
                    models.ImageField(blank=True, upload_to="maker_profile_image/"),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=20)),
                ("github_handle", models.CharField(blank=True, max_length=20)),
                ("indiehackers", models.CharField(blank=True, max_length=20)),
                ("personal_website", models.URLField(blank=True)),
                ("interviewed", models.BooleanField(default=False)),
            ],
            options={"db_table": "project_maker",},
        ),
    ]
