# Generated by Django 3.2.4 on 2021-08-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("makers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="maker", table=None,),
    ]
