# Generated by Django 3.2.4 on 2021-10-27 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("makers", "0002_alter_maker_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="maker",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
