# Generated by Django 3.2.4 on 2021-11-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("makers", "0003_maker_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="maker",
            name="short_bio",
            field=models.TextField(blank=True),
        ),
    ]
