name: Deploy Prod Workers

on: push

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: deployment/Dockerfile.workers
          tags: ghcr.io/${{ github.repository }}-workers

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@main
        with:
            server: ${{ secrets.CAPROVER_SERVER }}
            app: bwd-workers
            token: '${{ secrets.DEV_WORKERS_APP_TOKEN }}'
            image: ghcr.io/${{ github.repository }}-workers
