# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Build Python Dependencies
      run: |
          python -m pip install --upgrade pip
          pip3 install poetry
          poetry install
          npm install

  deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:

    - name: Pull the latest commit
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PORT: ${{ secrets.DO_PORT }}
        KEY: ${{ secrets.DO_SSHKEY }}
        script: |
          cd /var/www/builtwithdjango
          sudo git fetch --all
          sudo git reset --hard origin/master

    - name: Install dependencies
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PORT: ${{ secrets.DO_PORT }}
        KEY: ${{ secrets.DO_SSHKEY }}
        script: |
          export NODE_ENV=production
          cd /var/www/builtwithdjango
          source ./venv/bin/activate
          pip install -r requirements.txt
          sudo npm install
          npx webpack --mode=production

    - name: Build Project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PORT: ${{ secrets.DO_PORT }}
        KEY: ${{ secrets.DO_SSHKEY }}
        script: |
          cd /var/www/builtwithdjango
          source ./venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --noinput

    - name: Restart Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PORT: ${{ secrets.DO_PORT }}
        KEY: ${{ secrets.DO_SSHKEY }}
        script: |
          sudo systemctl restart bwd.gunicorn
          sudo systemctl restart nginx
