# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      
    - name: Build Python Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

    - name: Build NPM Dependencies
      run: npm install

  deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:

    - name: Install Dependencies 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PORT: ${{ secrets.DO_PORT }}
        KEY: ${{ secrets.DO_SSHKEY }}
        script: |
          cd /var/www/builtwithdjango
          sudo git fetch --all
          sudo git reset --hard origin/master
          pip install poetry
          poetry install
          poetry export -f requirements.txt > requirements.txt
          npm install

    - name: Build Project
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PORT: ${{ secrets.DO_PORT }}
        KEY: ${{ secrets.DO_SSHKEY }}
        script: |
          export NODE_ENV=production
          cd /var/www/builtwithdjango
          npx webpack --mode=production
          poetry run python manage.py migrate
          poetry run python manage.py collectstatic --noinput

    - name: Restart Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        USERNAME: ${{ secrets.DO_USERNAME }}
        PORT: ${{ secrets.DO_PORT }}
        KEY: ${{ secrets.DO_SSHKEY }}
        script: |
          sudo systemctl restart bwd.gunicorn
          sudo systemctl restart nginx
