# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

jobs:
  build:
    runs-on: self-hosted 
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build Python Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

    - name: Build NPM Dependencies
      run: npm install

    - name: Export requirements file
      run: poetry export -f requirements.txt > requirements.txt

    - name: Commit and push if bundles or dependencies changes changed
      run: |-
        git diff
        git config --global user.email "me@rasulkireev.com"
        git config --global user.name "Rasul's Bot"
        git diff --quiet || (git add requirements.txt && git commit -m "Updated requirements.txt")
        git push

  deploy:
    name: Deploy to DigitalOcean
    runs-on: self-hosted 
    needs: build
    # if: github.ref == 'refs/heaxds/master'
    steps:
    - name: Checkout master
      uses: actions/checkout@v1
    
    - name: Locate root dir and activate venv
      run: |
        cd /var/www/builtwithdjango
        source venv/bin/activate
        
    - name: Install Dependencies
      run: |
        python -m pip install -r requirements.txt
        npm install

    - name: Run Webpack
      run: |
        export NODE_ENV=production
        npx webpack

    - name: Migrate Database and Collect Static
      run: |
        python manage.py migrate
        python manage.py collectstatic -noinput
    
    - name: Restart Gunicorn and NGINX
      run: |
        sudo systemctl restart bwd.gunicorn
        sudo systemctl restart nginx
