# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      
    - name: Build Python Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

    - name: Build NPM Dependencies
      run: npm install

    - name: Run Webpack
      run: |
        export NODE_ENV=production
        npx webpack

    - name: Export requirements file
      run: poetry export -f requirements.txt > requirements.txt

    - name: Commit and push if bundles or dependencies changes changed
      run: |-
        git diff
        git config --global user.email "me@rasulkireev.com"
        git config --global user.name "Rasul's Bot"
        git diff --quiet || (git add assets/bundles/main.css assets/bundles/app.js && git commit -m "Updated webpack output")
        git diff --quiet || (git add requirements.txt && git commit -m "Updated requirements.txt")
        git push
